### ISSUE TITLE
ZWS and LZMA?

### ISSUE THREAD

**Issue by egberts** [rpedroso/swftools#3]
Is there any chance of having support for ZWS file format that uses LZMA?

If not, are there any GitHub clones having implemented the Release 19 of SWF File Format Specification for ActionScript v3?

**Comment by arkq** [comment]
If you (or anyone visiting this issue) are interested in the compression/decompression only, you can use my recently created utility called [swfpack](https://github.com/Arkq/swfpack). There are also some Python scripts, available of the web, for preforming such a task (e.g. [swfzip](https://github.com/OpenGG/swfzip)).

**Comment by egberts** [comment]
Thanks!
